# ## Postgres
# host: localhost
# port: 5432
# database: test
# user: postgres
# password: admin
# pool_size: 10
# # check whether db is accessible
# check: false

## MySQL
host: 127.0.0.1
port: 3306
database: storybuilder
user: comu
password: comu123$
pool_size: 10
# check whether db is accessible
check: false
